language: ruby
cache:
  bundler: true
  yarn: true
sudo: false
bundler_args: --path vendor --local --without development
env:
  - DATABASE_URL="mysql2://travis@localhost/myapp_test"
before_script:
  - mysql -u root -e "CREATE DATABASE myapp_test;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON myapp_test.* TO 'travis'@'%';";
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
script:
  - bin/rails db:migrate
  - RUN_COVERAGE=travis bin/rails test
  - bin/rails coverage:report
addons:
  code_climate:
    repo_token: a42e116d4d68894b025a60cb722a0b9ba2cf1c6497debb02993d0702284d2511
deploy:
  provider: script
  script: bash website/travis-deploy.sh
  on:
    branch: master
